### ISSUE TITLE
Versioneer

### ISSUE THREAD

**Issue by rougier** [benureau/r5#3]
Use of versioner make things overly complex for no obvious reason

**Comment by benureau** [comment]
Well, I agree with you that it makes things overly complex. But it is necessary to have accurate version info when the package is installed. I think, however, that providing a setup.py is of little interest: the most scientific code is supposed to produce results and figure, not be a library. People that want to distribute their code as a library know how to do it. My proposition:
- remove versioneer
- remove setup.py 
- put tests back outside of the package
This will make things much simpler.

**Comment by rougier** [comment]
Using a very simple setup.py you can use `python setup.py develop`

**Comment by benureau** [comment]
I removed versioneer, and the `r5` command line function (brought complexity but not much else). The code will now complain (and abort) if the git repository is not found or dirty, unless `dirty` is explicitly set to `True` in `walk_full`. As a result, a PyPi installation is not desirable. I'll update the documentation to reflect that `python setup.py develop` is preferred.
